version: '3.8'
services:
  ft_transcendence:
    container_name: ft_transcendence
    image: ft_transcendence
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    env_file:
      - ./services/web/backend/.env
    networks:
      - transnet
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:5044"   # ← udp://localhost:5044



networks:
  transnet:
    driver: bridge
    name: transnet
