global:
  scrape_interval: 15s

scrape_configs:
  # ─ Prometheus 
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # ─ Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # ─ ft_transcendence backend
  - job_name: 'app'
    metrics_path: /metrics          
    static_configs:
      - targets: ['ft_transcendence:4242']


