global:
  scrape_interval: 15s

scrape_configs:
  # ─ Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # ─ Node Exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


  # ─ ft_transcendence backend
  - job_name: 'app'
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ['ft_transcendence:443']
    tls_config:
      insecure_skip_verify: true
